package snowflake

import (
	"math/rand/v2"
	"strconv"
	"time"
)

const (
	DefaultEpoch int64 = 1420070400000 // 2015-01-01T00:00:00Z
)

// Snowflake represents a unique ID generated by a snowflake algorithm.
// It is a 64-bit integer represented as a string.
type Snowflake struct {
	value int64
	epoch int64
}

// String returns the string representation of the Snowflake.
func (s Snowflake) String() string {
	return strconv.FormatInt(s.value, 10)
}

// Int64 converts the Snowflake to an int64.
func (s Snowflake) Int64() int64 {
	return s.value
}

// New creates a new Snowflake from a string.
func New(value int64, epoch int64) Snowflake {
	return Snowflake{
		value: value,
		epoch: epoch,
	}
}

// NewFromInt64 creates a new Snowflake from an int64.
func NewFromString(s string, epoch int64) Snowflake {
	value, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return New(0, epoch)
	}
	return New(value, epoch)
}

// NewFromInt64 creates a new Snowflake from an int64.
func NewFromInt64(value int64, epoch int64) Snowflake {
	return New(value, epoch)
}

// NewRandom creates a new random Snowflake.
func NewRandom(epoch int64) Snowflake {
	return New(rand.Int64(), epoch)
}

// Time extracts the timestamp from the Snowflake.
func (s Snowflake) Time() time.Time {
	id := s.Int64()

	// Extract timestamp from Snowflake
	timestamp := (id >> 22) + DefaultEpoch

	return time.Unix(timestamp/1000, (timestamp%1000)*1000000)
}

// IsValid checks if the Snowflake is a valid Snowflake.
func (s Snowflake) IsValid() bool {
	return s.value > 0
}
