package snowflake

import (
	"encoding/json"
	"math/rand/v2"
	"strconv"
	"time"
)

const (
	DefaultEpoch int64 = 1420070400000 // 2015-01-01T00:00:00Z
)

// Snowflake represents a unique ID generated by a snowflake algorithm.
type Snowflake struct {
	value int64
	epoch int64
}

// String returns the string representation of the Snowflake.
func (s Snowflake) String() string {
	return strconv.FormatInt(s.value, 10)
}

// Int64 returns the int64 value of the Snowflake.
func (s Snowflake) Int64() int64 {
	return s.value
}

// Epoch returns the epoch used by this Snowflake.
func (s Snowflake) Epoch() int64 {
	return s.epoch
}

// Time extracts the timestamp from the Snowflake.
func (s Snowflake) Time() time.Time {
	timestamp := (s.value >> 22) + s.epoch
	return time.UnixMilli(timestamp)
}

// IsValid checks if the Snowflake has a valid non-zero value.
func (s Snowflake) IsValid() bool {
	return s.value > 0
}

// IsZero returns true if the Snowflake is zero/unset.
func (s Snowflake) IsZero() bool {
	return s.value == 0
}

// MarshalJSON implements json.Marshaler.
func (s Snowflake) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *Snowflake) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		var num int64
		if err := json.Unmarshal(data, &num); err != nil {
			return err
		}
		s.value = num
		if s.epoch == 0 {
			s.epoch = DefaultEpoch
		}
		return nil
	}
	val, err := strconv.ParseInt(str, 10, 64)
	if err != nil {
		return err
	}
	s.value = val
	if s.epoch == 0 {
		s.epoch = DefaultEpoch
	}
	return nil
}

// New creates a new Snowflake with the given value and epoch.
func New(value int64, epoch int64) Snowflake {
	return Snowflake{value: value, epoch: epoch}
}

// NewFromString creates a new Snowflake from a string.
func NewFromString(s string, epoch int64) Snowflake {
	value, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return New(0, epoch)
	}
	return New(value, epoch)
}

// NewFromInt64 creates a new Snowflake from an int64.
func NewFromInt64(value int64, epoch int64) Snowflake {
	return New(value, epoch)
}

// NewRandom creates a new random Snowflake.
func NewRandom(epoch int64) Snowflake {
	return New(rand.Int64(), epoch)
}

// Nullable represents a snowflake that can be null in JSON.
type Nullable struct {
	ID    Snowflake
	Valid bool
}

func (n *Nullable) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		n.Valid = false
		return nil
	}
	if err := n.ID.UnmarshalJSON(data); err != nil {
		return err
	}
	n.Valid = true
	return nil
}

func (n Nullable) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return n.ID.MarshalJSON()
}

// Slice represents a slice of snowflakes with JSON marshaling support.
type Slice []Snowflake

func (s *Slice) UnmarshalJSON(data []byte) error {
	var strs []string
	if err := json.Unmarshal(data, &strs); err != nil {
		return err
	}
	*s = make(Slice, len(strs))
	for i, str := range strs {
		(*s)[i] = NewFromString(str, DefaultEpoch)
	}
	return nil
}

func (s Slice) MarshalJSON() ([]byte, error) {
	strs := make([]string, len(s))
	for i, id := range s {
		strs[i] = id.String()
	}
	return json.Marshal(strs)
}
